DICT = dictionary-bst
TEST = excelMain3
STR = string-utility
DLL = dictionary-doublylinkedlist
VECTOR = dictionary-orderedvector
HASH = dictionary-hashtable
AUX = excelAux
EXCEL = excel

$(EXCEL) : $(DICT).cpp $(TEST).cpp $(STR).cpp $(DLL).cpp $(VECTOR).cpp $(HASH).cpp $(AUX).cpp
	g++ -o $(EXCEL) $(DICT).cpp $(TEST).cpp $(STR).cpp $(DLL).cpp $(VECTOR).cpp $(HASH).cpp $(AUX).cpp
